Storage.body.capacity=20
Storage.engine.capacity=30
Storage.accessory.capacity=50
Storage.car.capacity=20

Workers.count=4
Dealers.count=1
BodySuppliers.count=2
EngineSuppliers.count=2
AccessorySuppliers.count=3

Workers.delay=3000
Dealers.delay=3000
BodySuppliers.delay=4000
EngineSuppliers.delay=4000
AccessorySuppliers.delay=2000