storage.body.capacity=20
storage.engine.capacity=30
storage.accessory.capacity=50
storage.car.capacity=20
suppliers.accessory.count=2
suppliers.body.count=2
suppliers.engine.count=2
workers.count=4
dealers.count=2