Storage.body.capacity=5
Storage.engine.capacity=5
Storage.accessory.capacity=10
Storage.car.capacity=3

Workers.count=2
Dealers.count=1
BodySuppliers.count=1
EngineSuppliers.count=1
AccessorySuppliers.count=3

Workers.delay=3000
Dealers.delay=4000
BodySuppliers.delay=4000
EngineSuppliers.delay=3000
AccessorySuppliers.delay=2000